apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-engine
  namespace: ai-betting-platform
  labels:
    app: prediction-engine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prediction-engine
  template:
    metadata:
      labels:
        app: prediction-engine
    spec:
      containers:
      - name: prediction-engine
        image: ai-betting/prediction-engine:latest
        ports:
        - containerPort: 8001
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: url
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: prediction-engine-service
  namespace: ai-betting-platform
spec:
  selector:
    app: prediction-engine
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP