version: '3.8'

services:
  kong:
    image: kong:3.4
    container_name: ai-betting-kong
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_LISTEN=0.0.0.0:8002
    ports:
      - "8000:8000"   # Proxy
      - "8443:8443"   # Proxy SSL
      - "8001:8001"   # Admin API
      - "8002:8002"   # Admin GUI
    volumes:
      - ./kong.yml:/kong/declarative/kong.yml:ro
    networks:
      - kong-net
    restart: unless-stopped

  # Rate limiting with Redis
  redis:
    image: redis:7-alpine
    container_name: kong-redis
    networks:
      - kong-net
    restart: unless-stopped

networks:
  kong-net:
    driver: bridge